### ISSUE TITLE
Unable to render color escape codes

### ISSUE THREAD

**Issue by juanibiapina** [flok99/multitail#15]
Codes like the following: .[0;36m won't be converted to colors.

They will output the code itself, unlike if you do `tail -f directory/*`.

**Comment by flok99** [comment]
try:
multitail -cT ansi /var/log/messages

or whatever file

**Comment by juanibiapina** [comment]
Awesome

**Comment by dwatzke** [comment]
the problem is you have to specify this for each file, which means an ugly hack is needed if you want to use filename wildcards in shell

`multitail -s 3 $(for x in /colored_files/*; do echo "-cT ansi $x"; done)`

would it be possible to add an option so that this becomes the setting for all specified files from that option onwards? (similiarly to what -C does)

**Comment by djsmith42** [comment]
This is working for me without the ugly hack you reference:

```
multitail -cT ansi -Iw "path/to/logs/*" 1
```
