### ISSUE TITLE
Add support for 256 colors

### ISSUE THREAD

**Issue by vdun** [flok99/multitail#24]

**Comment by flok99** [comment]
Multitail does have support for 256 colors. You just need to recompile ncurses to support this. For some unknown reason some linux distributions still compile with 16 colors.

**Comment by vdun** [comment]
So how to specify custom 256 colors in my `colorscheme` ?
<pre>
colorscheme:test
cs_re:???:.*test.*
</pre>

**Comment by flok99** [comment]
Hmmm I'm not sure. It has been a while since I last looked at that code.
I don't think it is possible yet. But I welcome patches.
Maybe something that accepts:
cs_re:#rrggbb:...
e.g.:
cs_re:#e099fb:test



On Thu, Dec 3, 2015 at 5:02 PM, vdun <notifications@github.com> wrote:

> So how to specify custom 256 colors in my colorscheme ?
>
> colorscheme:test
> cs_re:???:.*test.*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flok99/multitail/issues/24#issuecomment-161690450>.
>



-- 
www.vanheusden.com  www.slimwinnen.nl | www.smartwinning.info

**Comment by Den2016** [comment]
I stumble over the same "problem". Multitail can handle 256 color but I cannot use it in the config?
I'm not a developer so I can't provide you with a patch but I can test it, if you or someone else implement it.
Please reopen the bug.
