### ISSUE TITLE
Backspace doesn't work in edit strip regular expressions dialog

### ISSUE THREAD

**Issue by madis** [flok99/multitail#5]
Steps to reproduce:

1. **[f]** (to filter)
2. **[a]** (to add)
3. **[c]** (choose column filter)
4. enter a word to serve as regex
5. try to correct using backspace. Doesn't work :(

**Comment by flok99** [comment]
May have been resolved by the delete-for-backspace fix.

**Comment by sixtyfive** [comment]
Unfortunately, the delete-for-backspace thing doesn't work for me, either (I'm on a regular PC running Linux), as (with or without it) delete just prints `J`. Curiously, multitail is the only place where that happens. One thing I did find out was that it only happens when multitail is running inside of [tmux](https://github.com/tmux/tmux), either locally or through SSH. No tmux, no backspace/delete problem. @flok99, might this Issue be reopened and possibly get a different title (the same thing happens in all the dialogs that have text entry)?
