### ISSUE TITLE
Repeatable crash after 2-3 days 

### ISSUE THREAD

**Issue by mandoonandy** [flok99/multitail#51]
I'm seeing multitail v6.4.2 crash repeatedly on Ubuntu 16.04.2 LTS. 

Hope somebody can help.

```
 --*- multitail 6.4.2 (C) 2003-2014 by folkert@vanheusden.com -*--

The following problem occured:
-----------------------------
Failed to reallocate a memory block to -4 bytes.
If this is a bug, please report the following information:
The last system call returned: 12 which means "Cannot allocate memory"
Execution path:
        0 multitail() [0x40d207]
        1 multitail() [0x4121dc]
        2 multitail() [0x41226f]
        3 multitail() [0x408d9f]
        4 multitail() [0x409913]
        5 multitail() [0x40cb90]
        6 multitail() [0x40cc2f]
        7 multitail() [0x403e8c]
        8 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f7109b36830]
        9 multitail() [0x403f99]
Terminated
```

**Comment by flok99** [comment]
What commandline do you use?

Op 27 mei 2017 9:48 a.m. schreef "mandoonandy" <notifications@github.com>:

I'm seeing multitail v6.4.2 crash repeatedly on Ubuntu 16.04.2 LTS. I love
multitail, especially the record of high CPU/Mem events that it keeps. So a
crash is quite annoying.

Hope somebody can help.

 --*- multitail 6.4.2 (C) 2003-2014 by folkert@vanheusden.com -*--

The following problem occured:
-----------------------------
Failed to reallocate a memory block to -4 bytes.
If this is a bug, please report the following information:
The last system call returned: 12 which means "Cannot allocate memory"
Execution path:
        0 multitail() [0x40d207]
        1 multitail() [0x4121dc]
        2 multitail() [0x41226f]
        3 multitail() [0x408d9f]
        4 multitail() [0x409913]
        5 multitail() [0x40cb90]
        6 multitail() [0x40cc2f]
        7 multitail() [0x403e8c]
        8 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)
[0x7f7109b36830]
        9 multitail() [0x403f99]
Terminated

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/flok99/multitail/issues/51>, or mute the thread

**Comment by mandoonandy** [comment]
This is my unedited command line:

```
multitail \
        -du \
        -mb 300MB \
        -s 2 -sn 3, \
        -t "Apache Access 400s only" -cS apache -e ' 40[0-9] ' -f /var/log/apache2/access.log \
        -t "Apache SSL Access 400s only" -cS apache -e ' 40[0-9] ' -f /var/log/apache2/davical_ssl_access.log \
        -t "Apache SSL Access" -cS apache -f /var/log/apache2/davical_ssl_access.log \
        -t "Davical Error" -cS apache -f /var/log/apache2/davical_error.log     \
        -t "Apache Error" -cS apache -f /var/log/apache2/error.log      \
        -t Fail2Ban -cS fail2ban -f /var/log/fail2ban.log \
        -t Syslog -cS syslog -ev "stunnel" -f /var/log/syslog \
```

**Comment by flok99** [comment]
oh hang on, it says "Cannot allocate memory"
so you're out of memory

**Comment by flok99** [comment]
you could limit the scrollback buffers a bit
